<?php
/**
 * Asset management utilities for Arata Vietnam theme
 * 
 * This file contains helper functions to automatically detect and load
 * hashed asset filenames generated by Vite build system.
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Get the hashed filename for a specific asset
 * 
 * @param string $assetName The base name of the asset (e.g., 'app', 'notifications')
 * @param string $extension The file extension (e.g., 'js', 'css')
 * @return string|false The hashed filename or false if not found
 */
function aratavietnam_get_asset_hash($assetName, $extension = 'js') {
    $dist_dir = get_template_directory() . '/dist';
    
    // Look for files matching the pattern: {assetName}-{hash}.{extension}
    $pattern = sprintf('/^%s-[a-zA-Z0-9]+\.%s$/', preg_quote($assetName, '/'), $extension);
    $files = scandir($dist_dir);
    
    foreach ($files as $file) {
        if (preg_match($pattern, $file)) {
            return $file;
        }
    }
    
    return false;
}

/**
 * Enqueue an asset with automatic hash detection
 * 
 * @param string $handle The script handle
 * @param string $assetName The base asset name
 * @param array $dependencies Script dependencies
 * @param string|bool|null $version Version string
 * @param bool $in_footer Whether to load in footer
 * @return bool Whether the asset was enqueued successfully
 */
function aratavietnam_enqueue_asset($handle, $assetName, $dependencies = [], $version = null, $in_footer = false) {
    $hashedFile = aratavietnam_get_asset_hash($assetName, 'js');
    
    if (!$hashedFile) {
        error_log(sprintf('Asset not found: %s', $assetName));
        return false;
    }
    
    $version = $version ?: wp_get_theme()->get('Version');
    $src = get_template_directory_uri() . '/dist/' . $hashedFile;
    
    wp_enqueue_script($handle, $src, $dependencies, $version, $in_footer);
    return true;
}

/**
 * Enqueue a CSS asset with automatic hash detection
 * 
 * @param string $handle The style handle
 * @param string $assetName The base asset name
 * @param string|bool|null $version Version string
 * @param string $media Media string
 * @return bool Whether the asset was enqueued successfully
 */
function aratavietnam_enqueue_style_asset($handle, $assetName, $version = null, $media = 'all') {
    $hashedFile = aratavietnam_get_asset_hash($assetName, 'css');
    
    if (!$hashedFile) {
        error_log(sprintf('CSS asset not found: %s', $assetName));
        return false;
    }
    
    $version = $version ?: wp_get_theme()->get('Version');
    $src = get_template_directory_uri() . '/dist/' . $hashedFile;
    
    wp_enqueue_style($handle, $src, [], $version, $media);
    return true;
}

/**
 * Get all hashed assets as an array for debugging
 * 
 * @return array Associative array of asset names to hashed filenames
 */
function aratavietnam_get_all_assets() {
    $dist_dir = get_template_directory() . '/dist';
    $assets = [];
    
    if (!is_dir($dist_dir)) {
        return $assets;
    }
    
    $files = scandir($dist_dir);
    $patterns = [
        'app' => '/^app-([a-zA-Z0-9]+)\.js$/',
        'notifications' => '/^notifications-([a-zA-Z0-9]+)\.js$/',
        'add-to-cart' => '/^add-to-cart-([a-zA-Z0-9]+)\.js$/',
        'product-single' => '/^product-single-([a-zA-Z0-9]+)\.js$/',
        'app-css' => '/^app-([a-zA-Z0-9]+)\.css$/',
        'editor-style' => '/^editor-style-([a-zA-Z0-9]+)\.css$/',
    ];
    
    foreach ($files as $file) {
        foreach ($patterns as $assetName => $pattern) {
            if (preg_match($pattern, $file, $matches)) {
                $assets[$assetName] = $file;
                break;
            }
        }
    }
    
    return $assets;
}